# This Dockerfile.toys is for use with toys.py
FROM python:alpine3.17
WORKDIR ./app
RUN pip install Flask
ENV FLASK_APP=toys.py
ENV FLASK_RUN_PORT=8000
COPY toys.py .
EXPOSE 8000
CMD ["flask", "run", "--host=0.0.0.0",, port=8000, debug=True]
