name: container
on:
  push

jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      container: #service-name-1:
        label: mycontainer
        #image: ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:latest
        image: dannyteaching/wordsvr-v2:latest
        ports:
           - 8000:8000
    steps:
    - name: check if running
      run: docker ps
        # run: echo "hi"

    - name: post a user example
      run: |
       result=$(curl --location 'http://localhost:8000/dishes' \
       --header 'Content-Type: application/json' \
       --data '{"name":"garlic bread"}')
    - name: check result
      run: |
        echo "response = "
        if $response
        then 
          echo  $response
        else
          echo "response is empty"
        fi

    - name: check if still running
      run: docker ps
#      service-name-2:
#        image: dockerhub-username:docker-image-2
#        ports:
#           - 4001:4000
#      - name: Get from service-1
#        run: http://localhost:3001/api/users
#
#      - name: Get from service-2
#        run: http://localhost:4001/api/items

#      - name: Set up Docker
#        uses: docker/setup-docker@v2

#          CODE= "curl -- location 'http://0.0.0.0:5001/dishes' \
#            --output /dev/null \
#            --request POST \
#            --header 'content-type: application/json' \
#            --data '{"name":"garlic bread"}' \
#          "
# --write-out '%{http_code}' \