name: container
on:
  push

jobs:
  job-name:
    runs-on: ubuntu-latest
    env:
      SECRET_USERNAME: ${{ secrets.DOCKER_COURSE_USERNAME }}
      SECRET_PW:  ${{ secrets.DOCKER_COURSE_PASSWORD }}

    steps:
    - name: Pull Docker image
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_COURSE_USERNAME }}
          password: ${{ secrets.DOCKER_COURSE_PASSWORD }}

#    - name: pull image
#      run: docker pull $DOCKER_USERNAME/wordsvr-2:latest

#    services:
#      wordcontainer:
#        image: $DOCKER_USERNAME/wordsvr-2:latest
##        image: dannyteaching/wordsvr-v2:latest
#        ports:
#           - 8000:8000

    - name: run container
      run: docker run -p 8080:8080 $DOCKER_USERNAME/wordsvr-2:latest

    - name: check if app is running
      run: docker ps

    - name: Print Secret
      run: echo $SECRET_USERNAME

    - name: create directory
      run: mkdir -p mypath

    - name: curl
      run: |
        echo curl --location --request POST 'http://127.0.0.1:8000/words?word=wood' >> mypath/results
        echo $(curl --location --request POST 'http://127.0.0.1:8000/words?word=wood') >> mypath/results
        echo curl --location --request POST 'http://127.0.0.1:8000/words?word=silver' >> mypath/results
        echo $(curl --location --request POST 'http://127.0.0.1:8000/words?word=silver') >> mypath/results
        echo curl --location --request GET 'http://127.0.0.1:8000/words' >> mypath/results
        echo $(curl --location --request GET 'http://127.0.0.1:8000/words') >> mypath/results

    - name: curl results
      run: cat mypath/results







