name: container
on:
  push

jobs:
  job-name:
    runs-on: ubuntu-latest
    services:
      wordcontainer: #service-name-1:
        #image: ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:latest
        image: dannyteaching/wordsvr-v2:latest
        ports:
           - 8000:8000
    steps:
    - uses: actions/checkout@v3
    - run: mkdir -p mypath

    - name: check if running
      run: docker ps

    - name: Curl
      run: |
        echo=$(curl --location --request POST 'http://127.0.0.1:8000/words?word=fine') >> mypath
        echo $(curl --location --request GET 'http://127.0.0.1:8000/words') >> mypath
#    - name: check result
#      run: |
#        echo "result = "
#        if $result
#        then
#          echo  $result
#        else
#          echo "result is empty"
#          fi

    - name: check if still running
      run: docker ps






