name: pull-and-test-toys
on:
  workflow_run:
    workflows: ["build-and-push-toys"]
    types:
      - completed
  workflow_dispatch:
jobs:
  execute:
    runs-on: ubuntu-latest
    services:
      toyscontainer:
        image: dannyteaching/toys:latest
        ports:
           - 80:8000
    steps:
      - name: Check if a p is running
        run: docker ps -a
      - name: create directory
        run: mkdir mypath
      - name: Fetch container logs (if exists) by image
        run: |
          CONTAINER_ID=$(docker ps -a -q -f ancestor=dannyteaching/toys:latest)
          if [ -n "$CONTAINER_ID" ]; then
            docker logs "$CONTAINER_ID"
          else
            echo "Container based on image dannyteaching/toys:latest not found."
          fi
        shell: bash

      - name: Inspect container
        run: |
          CONTAINER_ID=$(docker ps -a -q -f ancestor=dannyteaching/toys:latest)
          if [ -n "$CONTAINER_ID" ]; then
            docker inspect "$CONTAINER_ID"
          else
            echo "Container based on image dannyteaching/toys:latest not found."
          fi
        shell: bash

      - name: Test curl to localhost
        run: |
          curl -v http://127.0.0.1:80/toys
        shell: bash

#      - name: Curl from inside container
#        run: |
#          CONTAINER_ID=$(docker ps -a -q -f ancestor=dannyteaching/toys:latest)
#          if [ -n "$CONTAINER_ID" ]; then
#            docker exec "$CONTAINER_ID" curl -v http://127.0.0.1:8000/toys
#          else
#            echo "Container not found."
#          fi
#        shell: bash

      - name: check app again
        run: docker ps -a
      - name: curl tests
        run: |
          curl -v 'http://127.0.0.1:80/toys'
          --request GET 'http://127.0.0.1:80/toys'
          echo curl --location --request POST 'http://0.0.0.0:80/toys' \
            --header 'Content-Type: application/json' \
            --data '{ 
                "name": "blocks", 
                "descr": "12 building blocks", 
                "age": 3, 
                "price": 18.00 
            }' >> mypath/results 
          echo $(curl --location --request POST 'http://0.0.0.0:80/toys' \
            --header 'Content-Type: application/json' \
            --data '{ 
                "name": "blocks", 
                "descr": "12 building blocks", 
                "age": 3, 
                "price": 18.00 
            }') >> mypath/results
          echo curl --location --request GET 'http://127.0.0.1:80/toys' >> mypath/results
          echo $(curl --location --request GET 'http://127.0.0.1:80/toys') >> mypath/results
      - name: curl results
        if: always()
        run: cat mypath/results
#    regarding workflow_run:
#    https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed/62772822#62772822
