name: Test Docker Image
#on:
#  repository_dispatch:
#    types: trigger-test

on:
  workflow_dispatch
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: pull image
      run: |
        docker pull \
        ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:latest
    - name: echo
      run:  echo "pulled image"