name: Pull and Test Docker Image
#on:
#  repository_dispatch:
#    types: trigger-test
on:
  workflow_dispatch
  # see https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow

jobs:
  pull-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: test env.Image_name_dated
      run: echo $env.Image_name_dated

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_COURSE_USERNAME }}
        password: ${{ secrets.DOCKER_COURSE_PASSWORD }}
    - name: Run the image
      # run: docker run ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:latest in detached
      run:  docker run -d -p 80:80 ${{ secrets.DOCKER_COURSE_USERNAME }}/wordsvr-v2:latest

    - name: echo
      run:  echo "running image"
#    - name: test the image
#      run: |
#        CODE=`curl --write-out '%{http_code}' \
#        --silent \
#        --output /dev/null \
#        --request PUT \
#        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
#        --header 'content-type: application/json' \
#        --url 'https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.inputs.pr_num }}/merge' \
#        --data '{ \
#        "merge_method": "squash", \
#        "commit_title": "Squash and Merge for Pull Request ${{ github.event.inputs.pr_num }}", \
#        "commit_message": "expected sha value = ${{ github.event.inputs.pr_head_sha }}", \
#        "sha": "${{ github.event.inputs.pr_head_sha }}" \
#      }'`